### ISSUE TITLE
chimeric_reads_detection.sh Issues

### ISSUE THREAD

**Issue by rkyger-git** [NBorthLab/TargetedNanoporeSequencing#1]
Hello,

I ran into 2 issues running the "chimeric_reads_detection.sh" script, but I only solved 1 of them. 

I believe there is a typo on line 17 (see code chunk), as it causes an error message, changing this line to "done" (without the "<reads_mapping_to_plasmid.txt") fixes this issue. 
```shell
done<reads_mapping_to_plasmid.txt
``` 
Additionally, after fixing this issue, the scripts prints "Filter reads mapping to expression vector", and then freezes up, as running htop shows no processes running. 
I was wondering if the maintainer for this code has any insight into this issue?

**Comment by leitnerei** [comment]
Hi,
sorry for uploading this sloppy script. This one should work. 

Additionally, a few things changed since I started with the analysis.

1. If you are using minimap2 with version 2.19 or higher, then it is necessary to add the -r 500,500 flag otherwise chimeric reads might be wrongly classified as normal reads with a huge insertion and you would not be able to detect these reads.
2. The --cs flags is included which leads to a more precise aligning with minimap2.
3. In line 28 the start of the alinging postion of chimeric reads is included (cut -f3). This makes it easier to find the right integration sites later on.
4. The necessity to provide a second plasmid sequence (line 8) with different break points of the same plasmid is redundant. 

These changes are already made in the new script. Also before running this script adjust the path of the "exe" variable to minimap2 in line 13. As a result you will get an directory called integration sites containing your chimeric reads. 

Hopefully now it does work out. Otherwise please don't hesitate to open up another issue.
[chimeric_reads_detection_new.txt](https://github.com/NBorthLab/TargetedNanoporeSequencing/files/12671125/chimeric_reads_detection_new.txt)

**Comment by rkyger-git** [comment]
Hello,  

Thanks for the quick response and updated script.
I did have to make a few minor changes to get the script to work (see attached), but other than that, everything appears to be working fine.

[chimeric_reads_detection_new_2.txt](https://github.com/NBorthLab/TargetedNanoporeSequencing/files/12678151/chimeric_reads_detection_new_2.txt)
